In [1]:
import numpy as np

In [5]:
arr = [1,2,3,4]
arr = np.array(arr)
type(arr)

numpy.ndarray

In [8]:
for i in np.arange(1,10,2):
    print(i)

1
3
5
7
9


In [10]:
arr = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(arr)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(np.size(arr))

9


In [12]:
print(np.shape(arr))

(3, 3)


In [16]:
arr = [[1,2,3],[4,5,6]]
arr = np.array(arr)
print(arr)
print(np.shape(arr))

[[1 2 3]
 [4 5 6]]
(2, 3)


In [21]:
arr = np.reshape(arr,(3,2))             
print(arr)
print(np.shape(arr))
print(np.size(arr,0))                    #prints number of rows
print(np.size(arr,1))                    #prints number of columns

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
3
2


In [25]:
print(arr.dtype)

int32


In [26]:
print(arr.ndim)

2


In [29]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
arr = np.ones((4,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Eye function : identity vector

In [34]:
arr = np.eye(6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


empty function :  same as np.zeros

In [ ]:
------x----x-----x------x-----x----

random functions

1. random.rand : generates random values between 0 and 1

In [43]:
arr = np.random.rand(10)
print(arr)

[0.13910961 0.68213167 0.6615777  0.02259449 0.9665638  0.94001851
 0.36977649 0.73011224 0.31315183 0.45958637]


2. random.randint :  it generates values between integer range we define

In [47]:
arr = np.random.randint(low = 1, high = 10, size = 15)      #10 is not included
print(arr)

[5 8 1 8 9 3 3 7 4 4 5 1 6 8 7]


3. random.randn : generates random values in a random distribution

In [49]:
arr = np.random.randn(10)
print(arr)

[ 0.26417952 -0.30491648  0.4407524   1.9163974   0.09200368  0.30674298
  0.40481586  0.5990636   1.68171183 -0.96240208]


In [51]:
arr = np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [56]:
arr = [[1,2,3],[4,5,6],[7,9,8]]
arr = np.array(arr)
arr = arr.flatten()
print(arr)

[1 2 3 4 5 6 7 9 8]


np.logspace : same as linspace, except it generates value in log scale

In [58]:
arr = np.logspace(1,100,10)
print(arr)

[1.e+001 1.e+012 1.e+023 1.e+034 1.e+045 1.e+056 1.e+067 1.e+078 1.e+089
 1.e+100]


In [64]:
arr = [[1,2,3],[4,5,6],[7,9,8]]
arr = np.array(arr)
print(arr.min())
print(arr.min(axis=1))
print(arr.min(axis=0))
print(arr.max())
print(arr.max(axis=1))
print(arr.max(axis=0))
print(arr.sum())
print(arr.sum(axis=1))
print(arr.sum(axis=0))

1
[1 4 7]
[1 2 3]
9
[3 6 9]
[7 9 8]
45
[ 6 15 24]
[12 16 17]


seed function : if you write this begore random.randint, you get same random numbers every time that you got the first time, you can take seed as any arbitrary integer, it doesn't matter

In [66]:
np.random.seed(3)
print(np.random.randint(1,10,30))

[9 4 9 9 1 6 4 6 8 7 1 5 8 9 2 7 3 3 2 4 6 9 2 9 8 9 2 1 6 5]


Mathemeatical operations : +,-,*,/,//,**

Matrix multiplication : arr1.dot(arr2) > arr1 . arr2

Percentile function : you need to sort the array before using percentile

In [78]:
np.random.seed(3)
arr = np.array(np.random.randint(1,12,20))
arr = np.sort(arr)
print(arr)
print(np.percentile(arr,70))

[ 1  1  4  4  5  6  6  7  8  8  9  9  9  9 10 10 10 11 11 11]
9.299999999999999


mean, variance and standard deviation

In [79]:
print(np.mean(arr))
print(np.var(arr))
print(np.std(arr))

7.45
9.247499999999999
3.0409702399069936


filtering array

In [87]:
arr = np.arange(1,20)
print(arr[arr%2==0])
print(arr[arr%2!=0])
print(arr[arr>10])

[ 2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[11 12 13 14 15 16 17 18 19]


replacing the elements that don't satisfy the condition with something else, eg. replace odd numbers with zeros

In [89]:
arr[arr%2!=0] = 0
print(arr)

[ 0  2  0  4  0  6  0  8  0 10  0 12  0 14  0 16  0 18  0]


Transpose function

In [93]:
np.random.seed(2)
arr = np.random.randint(1,20,(2,3))
print(arr)
print(arr.T)     #transpose

[[ 9 16 14]
 [ 9 12 19]]
[[ 9  9]
 [16 12]
 [14 19]]


where function : it is similar to filtering an array, just using where function

In [128]:
arr = [1,3,5,4,6,7,9,8]
arr = np.array(arr)
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
----x----x-----x----x-----x----

In [138]:
from matplotlib.image import imread

In [141]:
img  = imread("Pic_to array.jpg")